const menu = [
  {
    id: 1,
    title: "Strained Pancake",
    category: "breakfast",
    price: 8.99,
    img: "./images/item-1.jpeg",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam vel a quibusdam fugit recusandae quae.",
  },
  {
    id: 2,
    title: "Double Hamburger",
    category: "lunch",
    price: 14.99,
    img: "./images/item-2.jpeg",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam vel a quibusdam fugit recusandae quae.",
  },
  {
    id: 3,
    title: "Godzilla Milkshake",
    category: "drinks",
    price: 4.99,
    img: "./images/item-6.jpeg",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam vel a quibusdam fugit recusandae quae.",
  },
  {
    id: 4,
    title: "Mixed Breakfast",
    category: "breakfast",
    price: 23.99,
    img: "./images/item-4.jpeg",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam vel a quibusdam fugit recusandae quae.",
  },
  {
    id: 5,
    title: "Egg Breakfast",
    category: "breakfast",
    price: 18.99,
    img: "./images/item-5.jpeg",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam vel a quibusdam fugit recusandae quae.",
  },
  {
    id: 6,
    title: "Oreo Dream",
    category: "drinks",
    price: 7.99,
    img: "./images/item-6.jpeg",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam vel a quibusdam fugit recusandae quae.",
  },
  {
    id: 7,
    title: "Sandwich",
    category: "breakfast",
    price: 10.99,
    img: "./images/item-7.jpeg",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam vel a quibusdam fugit recusandae quae.",
  },
  {
    id: 8,
    title: "American Classic",
    category: "lunch",
    price: 17.99,
    img: "./images/item-8.jpeg",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam vel a quibusdam fugit recusandae quae.",
  },
  {
    id: 9,
    title: "Vanilla Flavored Milkshake",
    category: "drinks",
    price: 8.99,
    img: "./images/item-9.jpeg",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam vel a quibusdam fugit recusandae quae.",
  },
  {
    id: 10,
    title: "Dallas Steak",
    category: "lunch",
    price: 34.99,
    img: "./images/item-10.jpeg",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam vel a quibusdam fugit recusandae quae.",
  },
];

export default menu;
